### ISSUE TITLE
undefined method `inheritance_column' for Class

### ISSUE THREAD

**Issue by gerryhd** [activeadmin/activeadmin-mongoid#107]
I'm using the rails4-mongo5 branch, currently migrating from rails_admin to active_admin.

Everything works fine at first (installation), but as soon as I create a resource and try to access it in the dashboard I get:

> undefined method `inheritance_column' for Home:Class

Not quite sure what else I should say now; I have followed the instructions in the README of the branch but the error persists.

Any idea how I could work around or fix this error? What I already tried was forking and changing inheritance_column to _types but it must have created more errors rather than fixing them (subsequent errors kept popping up no matter how many I tried to "fix").

**Comment by boie0025** [comment]
@gerryhd please post a backtrace, and a pared down copy of the "Home" class, we'll take a look and see why you might be getting this error.

**Comment by gerryhd** [comment]
```
NoMethodError - undefined method `inheritance_column' for Home:Class:
  activeadmin (1.0.0) lib/active_admin/resource/attributes.rb:35:in `sti_col?'
  activeadmin (1.0.0) lib/active_admin/resource/attributes.rb:27:in `reject_col?'
  activeadmin (1.0.0) lib/active_admin/resource/attributes.rb:8:in `block in default_attributes'
  activeadmin (1.0.0) lib/active_admin/resource/attributes.rb:7:in `default_attributes'
  activeadmin (1.0.0) lib/active_admin/resource.rb:180:in `resource_attributes'
  activeadmin (1.0.0) lib/active_admin/resource.rb:188:in `content_columns'
  activeadmin (1.0.0) lib/active_admin/filters/resource_extension.rb:112:in `default_filters'
  activeadmin (1.0.0) lib/active_admin/filters/resource_extension.rb:96:in `filter_lookup'
  activeadmin (1.0.0) lib/active_admin/filters/resource_extension.rb:25:in `filters'
  activeadmin (1.0.0) lib/active_admin/filters/resource_extension.rb:145:in `block in filters_sidebar_section'
  activeadmin (1.0.0) lib/active_admin/helpers/optional_display.rb:25:in `display_on?'
  activeadmin (1.0.0) lib/active_admin/resource/sidebars.rb:17:in `block in sidebar_sections_for'
  activeadmin (1.0.0) lib/active_admin/resource/sidebars.rb:17:in `sidebar_sections_for'
  activeadmin (1.0.0) lib/active_admin/views/pages/base.rb:114:in `sidebar_sections_for_action'
  activeadmin (1.0.0) lib/active_admin/views/pages/base.rb:138:in `skip_sidebar?'
  activeadmin (1.0.0) lib/active_admin/views/pages/base.rb:76:in `build_page_content'
  activeadmin (1.0.0) lib/active_admin/views/pages/base.rb:54:in `block (2 levels) in build_page'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
  activeadmin (1.0.0) lib/active_admin/views/pages/base.rb:50:in `block in build_page'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  activeadmin (1.0.0) lib/active_admin/views/pages/base.rb:49:in `build_page'
  activeadmin (1.0.0) lib/active_admin/views/pages/base.rb:10:in `build'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
  arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  activeadmin (1.0.0) app/views/active_admin/resource/index.html.arb:2:in `block in __home_gerry__rvm_gems_ruby_______homiemx_gems_activeadmin_______app_views_active_admin_resource_index_html_arb___4419455023637826552_70077157862700'
  arbre (1.1.1) lib/arbre/context.rb:45:in `initialize'
  activeadmin (1.0.0) app/views/active_admin/resource/index.html.arb:1:in `__home_gerry__rvm_gems_ruby_______homiemx_gems_activeadmin_______app_views_active_admin_resource_index_html_arb___4419455023637826552_70077157862700'
  actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5) lib/action_view/template.rb:143:in `render'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.5) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.5) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.5) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.5) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/gerry/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.5) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:43:in `render'
  wicked_pdf (1.1.0) lib/wicked_pdf/pdf_helper.rb:42:in `render_with_wicked_pdf'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  responders (2.1.0) lib/action_controller/responder.rb:236:in `default_render'
  responders (2.1.0) lib/action_controller/responder.rb:170:in `to_html'
  responders (2.1.0) lib/responders/flash_responder.rb:107:in `to_html'
  responders (2.1.0) lib/action_controller/responder.rb:163:in `respond'
  responders (2.1.0) lib/action_controller/responder.rb:156:in `call'
  responders (2.1.0) lib/action_controller/respond_with.rb:203:in `respond_with'
  inherited_resources (1.7.2) lib/inherited_resources/actions.rb:7:in `index'
  activeadmin (1.0.0) lib/active_admin/resource_controller/streaming.rb:12:in `index'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  rack (1.6.4) lib/rack/deflater.rb:35:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  airbrake (5.3.0) lib/airbrake/rack/middleware.rb:22:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.13.4) lib/puma/server.rb:541:in `handle_request'
  puma (2.13.4) lib/puma/server.rb:388:in `process_client'
  puma (2.13.4) lib/puma/server.rb:270:in `block in run'
  puma (2.13.4) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

The ActiveAdmin related class "Home" is empty

```
ActiveAdmin.register Home do
# See permitted parameters documentation:
# https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#setting-up-strong-parameters
#
# permit_params :list, :of, :attributes, :on, :model
#
# or
#
# permit_params do
#   permitted = [:permitted, :attributes]
#   permitted << :other if params[:action] == 'create' && current_user.admin?
#   permitted
# end

end
```

**Comment by gerryhd** [comment]
So I added a class method "inheritance_column" to my model Home and gave it a hardcoded value and it works now, but what exactly is "inheritance_column" for and why would the gem ask me for it? Obviously hardcoding some value into it isn't the best solution so I'd like to know how to fix this properly.

**Comment by boie0025** [comment]
@gerryhd is the Home model an STI model?  inheritance_column is supposed to tell the model which column to get the STI class from (eg :_type)

**Comment by boie0025** [comment]
@gerryhd Did you resolve this issue?  I'm hoping it was just that it was an STI model?

**Comment by gerryhd** [comment]
inheritance_column is a deprecated method of ActiveRecord::base . I think ActiveAdmin did recognise my models as STI models, but none of them really are as far as I'm concerned. So I followed instructions here https://apidock.com/rails/ActiveRecord/Base/inheritance_column/class#364-two-ways-to-disable-single-table-inheritance , specifically the second option, and added them (via `extended Class` ) to all the models I'll need for ActiveAdmin. It's been working fine since.

**Comment by boie0025** [comment]
👍 Sounds good, thanks for the info!
